"""Pydantic data models for the commentary pipeline.

Defines types for generated commentary, Q&A questions, audience display
updates, and commentary-layer capture events.
"""

from __future__ import annotations

from pydantic import BaseModel

from src.capture.models import CaptureEvent

# ---------------------------------------------------------------------------
# Core commentary types
# ---------------------------------------------------------------------------


class Commentary(BaseModel):
    """Generated commentary for a single demo.

    Contains the full text, sentence-level breakdown for streaming to
    TTS and display, and an emotion map for per-sentence Cartesia emotion
    control.
    """

    team_name: str
    text: str
    sentences: list[str]
    emotion_map: dict[int, str]  # sentence index -> Cartesia emotion tag
    generated_at: float


class QAQuestion(BaseModel):
    """A single Q&A question generated by Arbiter."""

    text: str
    context: str  # what observation prompted this question


class DisplayUpdate(BaseModel):
    """Message pushed to the audience display via WebSocket."""

    type: str  # "commentary", "question", "score", "clear"
    text: str
    team_name: str
    timestamp: float


# ---------------------------------------------------------------------------
# Commentary events extending CaptureEvent
# ---------------------------------------------------------------------------


class QARequested(CaptureEvent):
    """Emitted when human judges defer a Q&A question to Arbiter."""

    event_type: str = "qa_requested"
    team_name: str


class CommentaryDelivered(CaptureEvent):
    """Emitted when commentary generation and delivery completes."""

    event_type: str = "commentary_delivered"
    team_name: str
    commentary_text: str


class TTSSpeaking(CaptureEvent):
    """Emitted when TTS playback begins (audio capture should mute)."""

    event_type: str = "tts_speaking"


class TTSFinished(CaptureEvent):
    """Emitted when TTS playback ends (audio capture can resume)."""

    event_type: str = "tts_finished"
